### ISSUE TITLE
Error clicking tag in settings -> tags w/ restriction

### ISSUE THREAD

**Issue by fryfrog** [Sonarr/Sonarr#4683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Settings -> Tags, click a tag w/ restriction. Sad Panda.

```
TypeError: e.split is not a function
```

![](https://i.imgur.com/21o1Okg.png)

### Expected Behavior

The Tag dialog should pop up.

### Steps To Reproduce

Settings -> Tags, click a tag w/ a restriction.

### Environment

```markdown
- OS: Arch Linux
- Sonarr: 3.0.6.1350 w/ Mono 6.12
- Using Reverse Proxy: nginx
- Browser: Chrome 94.0.4606.71
```

### What branch are you running?

Develop

### Anything else?

Why is "Anything else?" *required*?

**Comment by bakerboy448** [comment]
Likely broke with https://github.com/Sonarr/Sonarr/commit/ada01a1116065bbe6c3bed83009b6713a2005ffc#diff-86e71ec6a184105d6c250e7296298e95366cc709d90c0ee13cf4403b77641e0b
